CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_id INTEGER DEFAULT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT NULL,
    completed BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    due_date DATETIME DEFAULT NULL
);

CREATE TRIGGER update_task_timestamp
AFTER UPDATE ON tasks
FOR EACH ROW
WHEN OLD.updated_at = NEW.updated_at OR OLD.updated_at is NULL
BEGIN
    UPDATE tasks
    SET UPDATED_AT = CURRENT_TIMESTAMP
    WHERE id = OLD.id;
END;
